server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: 'salascodes'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
